### ISSUE TITLE
Script fails

### ISSUE THREAD

**Issue by fblais** [D3PSI/nasa-wallpaper-changer#1]
Hi.
I installed this in Linux Mint 20.1, which is based on Ubuntu 20.04LTS.

I'm getting this:
python3 /usr/local/bin/nasa-wallpaper-changer/nasa-wallpaper-changer.py
Traceback (most recent call last):
  File "/usr/local/bin/nasa-wallpaper-changer/nasa-wallpaper-changer.py", line 84, in <module>
    time.sleep(120)
NameError: name 'time' is not defined

The end of the script reads:
if __name__ == "__main__":

    schedule.every().hour.do(main)

    while True:

        schedule.run_pending()
        time.sleep(120)

Thankis in advance!

**Comment by cedricschwyter** [comment]
Hi @fblais,
I have pushed a commit on master, which you should be able to use and run now.
Closing this issue.
